// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhq6olwHG62Yu_4aE3IcOYM7YokuGTj9I',
    appId: '1:270912304322:web:3492d65d4e9d9275d3f75b',
    messagingSenderId: '270912304322',
    projectId: 'task1-ae96f',
    authDomain: 'task1-ae96f.firebaseapp.com',
    storageBucket: 'task1-ae96f.firebasestorage.app',
    measurementId: 'G-KHZREPRHFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFK-DfDbW44ucM0wOK_nCYleV4P7NB9-Y',
    appId: '1:270912304322:android:2164e4cedbf2c293d3f75b',
    messagingSenderId: '270912304322',
    projectId: 'task1-ae96f',
    storageBucket: 'task1-ae96f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw3Yff3e8wKjDWOrY6p_N09pFF3fSt_Qs',
    appId: '1:270912304322:ios:cd898d179aaeadc5d3f75b',
    messagingSenderId: '270912304322',
    projectId: 'task1-ae96f',
    storageBucket: 'task1-ae96f.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw3Yff3e8wKjDWOrY6p_N09pFF3fSt_Qs',
    appId: '1:270912304322:ios:cd898d179aaeadc5d3f75b',
    messagingSenderId: '270912304322',
    projectId: 'task1-ae96f',
    storageBucket: 'task1-ae96f.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhq6olwHG62Yu_4aE3IcOYM7YokuGTj9I',
    appId: '1:270912304322:web:1429e0414d7d08ebd3f75b',
    messagingSenderId: '270912304322',
    projectId: 'task1-ae96f',
    authDomain: 'task1-ae96f.firebaseapp.com',
    storageBucket: 'task1-ae96f.firebasestorage.app',
    measurementId: 'G-8N7QBXVWNZ',
  );
}
